In [1]:
import numpy as np

In [2]:
print("NumPy version:", np.__version__)
np.show_config()

NumPy version: 1.26.4
Build Dependencies:
  blas:
    detection method: pkgconfig
    found: true
    include directory: C:/Users/Ashish Soti/anaconda3/Library/include
    lib directory: C:/Users/Ashish Soti/anaconda3/Library/lib
    name: mkl-sdl
    openblas configuration: unknown
    pc file directory: C:\b\abs_c1ywpu18ar\croot\numpy_and_numpy_base_1708638681471\_h_env\Library\lib\pkgconfig
    version: '2023.1'
  lapack:
    detection method: internal
    found: true
    include directory: unknown
    lib directory: unknown
    name: dep1868282989520
    openblas configuration: unknown
    pc file directory: unknown
    version: 1.26.4
Compilers:
  c:
    commands: cl.exe
    linker: link
    name: msvc
    version: 19.29.30154
  c++:
    commands: cl.exe
    linker: link
    name: msvc
    version: 19.29.30154
  cython:
    commands: cython
    linker: cython
    name: cython
    version: 3.0.8
Machine Information:
  build:
    cpu: x86_64
    endian: little
    family: x86_64
   

In [3]:
null_vector = np.zeros(10)
print(null_vector)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [4]:
arr = np.zeros(10)
memo = arr.nbytes
print(memo)

80


In [5]:
help(np.add)

Help on ufunc:

add = <ufunc 'add'>
    add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])
    
    Add arguments element-wise.
    
    Parameters
    ----------
    x1, x2 : array_like
        The arrays to be added.
        If ``x1.shape != x2.shape``, they must be broadcastable to a common
        shape (which becomes the shape of the output).
    out : ndarray, None, or tuple of ndarray and None, optional
        A location into which the result is stored. If provided, it must have
        a shape that the inputs broadcast to. If not provided or None,
        a freshly-allocated array is returned. A tuple (possible only as a
        keyword argument) must have length equal to the number of outputs.
    where : array_like, optional
        This condition is broadcast over the input. At locations where the
        condition is True, the `out` array will be set to the ufunc result.
        Elsewhere, the `out` array wi

In [6]:
null_vector = np.zeros(10)
null_vector[4] = 1
print(null_vector)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


In [7]:
vector = np.arange(10, 50)
print(vector)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


In [8]:

vector = np.array([1, 2, 3, 4, 5])

reversed_vector = vector[::-1]

print("Original vector:", vector)
print("Reversed vector:", reversed_vector)

Original vector: [1 2 3 4 5]
Reversed vector: [5 4 3 2 1]


In [9]:
matrix = np.arange(9).reshape(3, 3)
print("1. 3x3 Matrix with values ranging from 0 to 8:")
print(matrix)

1. 3x3 Matrix with values ranging from 0 to 8:
[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [10]:
arr = np.array([1, 2, 0, 0, 4, 0])
non_zero_indices = np.nonzero(arr)
print("\n2. Indices of non-zero elements:")
print(non_zero_indices)


2. Indices of non-zero elements:
(array([0, 1, 4], dtype=int64),)


In [11]:
identity_matrix = np.eye(3)
print("\n3. 3x3 Identity Matrix:")
print(identity_matrix)


3. 3x3 Identity Matrix:
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [12]:
random_array = np.random.random((3, 3, 3))
print("\n4. 3x3x3 Array with random values:")
print(random_array)


4. 3x3x3 Array with random values:
[[[0.6284263  0.50553916 0.0074886 ]
  [0.03061249 0.99546734 0.00662674]
  [0.26015616 0.91017379 0.76136239]]

 [[0.91649828 0.39657942 0.2132181 ]
  [0.13219479 0.14179987 0.53941639]
  [0.37879462 0.14012898 0.24689999]]

 [[0.76860121 0.27925597 0.91300364]
  [0.65127207 0.34094606 0.30544406]
  [0.22385483 0.94240706 0.39567098]]]


In [13]:
array_10x10 = np.random.random((10, 10))
min_value = np.min(array_10x10)
max_value = np.max(array_10x10)
print("\n5. 10x10 Array with random values:")
print(array_10x10)
print("\n   Minimum value:", min_value)
print("   Maximum value:", max_value)


5. 10x10 Array with random values:
[[7.30730426e-01 5.93327000e-01 1.42018891e-01 8.64257493e-01
  4.11940470e-01 3.83924231e-01 4.80041015e-01 3.46284828e-01
  3.65535309e-01 4.94819984e-01]
 [2.66727568e-01 7.06844686e-01 4.97112288e-01 7.98418724e-01
  8.27807986e-02 4.05957632e-01 9.32342031e-01 2.01153836e-01
  2.73897442e-01 4.30808881e-01]
 [2.73238323e-01 9.84995519e-01 9.17829349e-01 2.98882847e-01
  2.03459944e-01 2.94695632e-01 6.08207540e-01 2.64024515e-01
  8.61212505e-01 2.25961029e-01]
 [7.81278460e-01 8.23566890e-01 2.01304360e-01 1.96002062e-01
  9.09518057e-02 1.62212218e-01 3.24751263e-01 9.84271758e-01
  7.70989564e-01 4.00481036e-01]
 [2.44881354e-01 6.46899510e-01 2.24704282e-04 2.54718257e-01
  1.66934755e-01 6.67655113e-01 7.04693206e-01 4.30061382e-01
  8.48268659e-01 8.82899225e-01]
 [8.61439732e-01 6.20204593e-01 4.08865668e-01 7.31679834e-01
  2.19224697e-01 8.65243247e-01 3.51798125e-01 7.52438373e-01
  5.74214993e-01 3.39847604e-01]
 [1.20167204e-01 6.625

In [14]:
random_vector = np.random.random(30)
mean_value = np.mean(random_vector)
print("1. Mean value of the random vector:")
print(mean_value)

1. Mean value of the random vector:
0.417357486613456


In [15]:
array_2d = np.ones((5, 5))
array_2d[1:-1, 1:-1] = 0
print("\n2. 2D array with 1 on the border and 0 inside:")
print(array_2d)


2. 2D array with 1 on the border and 0 inside:
[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


In [16]:
existing_array = np.ones((3, 3))
new_array = np.pad(existing_array, pad_width=1, mode='constant', constant_values=0)
print("\n3. Array with a border of 0's added around it:")
print(new_array)


3. Array with a border of 0's added around it:
[[0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 0.]
 [0. 1. 1. 1. 0.]
 [0. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0.]]


In [17]:
matrix = np.diag(1 + np.arange(4), k=-1)
print("\n4. 5x5 Matrix with values 1,2,3,4 just below the diagonal:")
print(matrix)



4. 5x5 Matrix with values 1,2,3,4 just below the diagonal:
[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


In [18]:
checkerboard = np.zeros((8, 8), dtype=int)
checkerboard[1::2, ::2] = 1
checkerboard[::2, 1::2] = 1
print("\n5. 8x8 Matrix filled with a checkerboard pattern:")
print(checkerboard)


5. 8x8 Matrix filled with a checkerboard pattern:
[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


In [19]:
array_shape = (6, 7, 8)
total_elements = np.prod(array_shape)

index_100 = np.unravel_index(99, array_shape)

print("Index of the 100th element (x, y, z):", index_100)

Index of the 100th element (x, y, z): (1, 5, 3)


In [20]:
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1

False