In [2]:
# Importing NumPy
import numpy as np

# Creating Arrays
# Creating an array from a list:
arr = np.array([1, 2, 3, 4, 5])
print("Array from list:", arr)

# Creating a 2D array:
arr_2d = np.array([[1, 2, 3], [4, 5, 6]])
print("2D array:\n", arr_2d)

# Creating arrays of zeros, ones, and a constant value:
zeros = np.zeros((3, 3))
print("Array of zeros:\n", zeros)

ones = np.ones((2, 4))
print("Array of ones:\n", ones)

full = np.full((2, 3), 7)
print("Array of sevens:\n", full)

# Creating an array with a range of values:
range_array = np.arange(0, 10, 2)  # [0, 2, 4, 6, 8]
print("Range array:", range_array)

# Creating an array with linearly spaced values:
linspace_array = np.linspace(0, 1, 5)  # [0.  , 0.25, 0.5 , 0.75, 1.  ]
print("Linspace array:", linspace_array)

# Basic Array Operations
# Element-wise addition, subtraction, multiplication, and division:
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])

add = arr1 + arr2
print("Addition:", add)

subtract = arr1 - arr2
print("Subtraction:", subtract)

multiply = arr1 * arr2
print("Multiplication:", multiply)

divide = arr1 / arr2
print("Division:", divide)

# Element-wise mathematical functions:
square = np.square(arr1)
print("Square:", square)

sqrt = np.sqrt(arr1)
print("Square root:", sqrt)

exp = np.exp(arr1)
print("Exponential:", exp)

# Array Attributes
# Shape of the array:
shape = arr_2d.shape  # (2, 3)
print("Shape:", shape)

# Number of dimensions:
ndim = arr_2d.ndim  # 2
print("Number of dimensions:", ndim)

# Size of the array (number of elements):
size = arr_2d.size  # 6
print("Size:", size)

# Data type of the elements:
dtype = arr.dtype  # dtype('int64')
print("Data type:", dtype)

# Reshaping and Resizing
# Reshaping an array:
reshaped = arr_2d.reshape(3, 2)
print("Reshaped array:\n", reshaped)

# Flattening an array:
flattened = arr_2d.flatten()
print("Flattened array:", flattened)

# Indexing and Slicing
# Indexing:
element = arr[2]  # 3
print("Element at index 2:", element)

# Slicing:
sub_array = arr[1:4]  # [2, 3, 4]
print("Sliced array:", sub_array)


Array from list: [1 2 3 4 5]
2D array:
 [[1 2 3]
 [4 5 6]]
Array of zeros:
 [[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
Array of ones:
 [[1. 1. 1. 1.]
 [1. 1. 1. 1.]]
Array of sevens:
 [[7 7 7]
 [7 7 7]]
Range array: [0 2 4 6 8]
Linspace array: [0.   0.25 0.5  0.75 1.  ]
Addition: [5 7 9]
Subtraction: [-3 -3 -3]
Multiplication: [ 4 10 18]
Division: [0.25 0.4  0.5 ]
Square: [1 4 9]
Square root: [1.         1.41421356 1.73205081]
Exponential: [ 2.71828183  7.3890561  20.08553692]
Shape: (2, 3)
Number of dimensions: 2
Size: 6
Data type: int32
Reshaped array:
 [[1 2]
 [3 4]
 [5 6]]
Flattened array: [1 2 3 4 5 6]
Element at index 2: 3
Sliced array: [2 3 4]
